### ISSUE TITLE
Unable to train on CPU

### ISSUE THREAD

**Issue by smallfade** [AllenInstitute/aics-ml-segmentation#3]
Added a device item in the config file to train on cpu, and it looks ok in the initialization message, but an error occur when start training. I was able to train on the GPU with the same config (except device).
Any idea how to make it work on CPU? I got a very weak GPU but powerful CPUs.
```
2019-09-06 15:55:04,481 [MainThread] INFO ModelTrainer - Number of learnable params 17729902
Loading checkpoint '/mnt/home/jingliulj/Images/laminin_staining/checkpoint/checkpoint_epoch_0.pytorch'...
2019-09-06 15:55:06,394 [MainThread] INFO ModelTrainer - Sending the model to 'cpu'
prepare the data ... ...
/mnt/home/jingliulj/Images/aics-ml-segmentation/aicsmlsegment/utils.py:24: YAMLLoadWarning: calling yaml.load() without Loader=... is depre$
  return yaml.load(open(config_file, 'r'))
^M0it [00:00, ?it/s]^M0it [00:07, ?it/s]
Traceback (most recent call last):
  File "/mnt/home/jingliulj/miniconda3/envs/img/bin/dl_train", line 11, in <module>
    load_entry_point('aicsmlsegment', 'console_scripts', 'dl_train')()
  File "/mnt/home/jingliulj/Images/aics-ml-segmentation/aicsmlsegment/bin/train.py", line 41, in main
    trainer.train()
  File "/mnt/home/jingliulj/Images/aics-ml-segmentation/aicsmlsegment/training_utils.py", line 264, in train
    outputs = model(inputs)
  File "/mnt/home/jingliulj/miniconda3/envs/img/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/home/jingliulj/Images/aics-ml-segmentation/aicsmlsegment/Net3D/unet_xy.py", line 90, in forward
    down1 = self.ec1(x)
  File "/mnt/home/jingliulj/miniconda3/envs/img/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/home/jingliulj/miniconda3/envs/img/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/mnt/home/jingliulj/miniconda3/envs/img/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/home/jingliulj/miniconda3/envs/img/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 478, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

```

**Comment by smallfade** [comment]
managed to make it start training on CPU by changing parts of source code in custom_loss.py, model_utils.py and training_utils.py. It would be better to do a device check in the initialization.

**Comment by jxchen01** [comment]
Thanks for your valuable feedback. As we point out at the beginning of REAMDE, we assume GPU is properly setup before running the deep learning training. That's why we don't have a device check in initialization. We found that training on CPU is too hard for 3D data.

For now, I would suggest to try running the trainining on google colab, where free TITAN X GPUs (if I remember correctly) are available. The training/testing part of our segmenter should be completely compatible on google colab. 

Meanwhile, we are actively investigating other cloud-based solution for users to run our segmenters without local GPU, where we can have more flexibilty to deeply customize the environment than google colab. Stay tuned :)

Let me know if there is anythign else  I can help.

**Comment by smallfade** [comment]
> Thanks for your valuable feedback. As we point out at the beginning of REAMDE, we assume GPU is properly setup before running the deep learning training. That's why we don't have a device check in initialization. We found that training on CPU is too hard for 3D data.
> 
> For now, I would suggest to try running the trainining on google colab, where free TITAN X GPUs (if I remember correctly) are available. The training/testing part of our segmenter should be completely compatible on google colab.
> 
> Meanwhile, we are actively investigating other cloud-based solution for users to run our segmenters without local GPU, where we can have more flexibilty to deeply customize the environment than google colab. Stay tuned :)
> 
> Let me know if there is anythign else I can help.

That's great to know you're working on a cloud-based solution. I think pytorch could work with TPU now, do you have a plan to make your pipeline work with TPU? I am moving my project to the colab actually, but you know, the data is not small and we don't have a big Google drive.  Anyway, Imay be able to have a GPU cluster to use locally. 
 
Do you have any suggestion to make the segmenter work with multi-channel 2D data? We have many old data, which I think they should be ok to use as training data, if there's an easy way to include it. Currently, I'm trying to convert the 2D image to 3D by replicating the layers, and this pseudo-3D data could work with your classic segmentation pipeline, but still testing the DL part.  But this method is actually wasting a lot of resources and I don't want to mess up your code and model to make it work with 2D data.

**Comment by jxchen01** [comment]
we don't have a plan to support TPU in the near future. It is very true that transferring data back and forth between local machine and cloud would be troublesome. That is another reason why we didn't adopt colab. ideally, we want the cloud solution to handle data transfer easily.

For 2D data, I plan to push an update soon to the repo which adds support for 2D (either multi-channel or single channel). Maybe within 2 weeks.

**Comment by smallfade** [comment]
> we don't have a plan to support TPU in the near future. It is very true that transferring data back and forth between local machine and cloud would be troublesome. That is another reason why we didn't adopt colab. ideally, we want the cloud solution to handle data transfer easily.
> 
> For 2D data, I plan to push an update soon to the repo which adds support for 2D (either multi-channel or single channel). Maybe within 2 weeks.

Great to know your plan. Thank you for your work. I think it's a very promising tool and would help us a lot. It would benefit more if the community can share the data and have a starting DL model to perform a transfer learning.

**Comment by jxchen01** [comment]
This is the sample data users can use to test our deep learning demo:

https://allencell.quiltdata.com/b/quilt-aics/packages/aics/laminb1_sample_data/tree/1563914641/

Also, just FYI, our institute releases tons of image data to the pubic: https://www.allencell.org/data-downloading.html#ProgrammaticAccess

Regarding pre-trained models and transfer learning, I actually have a different opinion. Based on my experience, transfer learning from a model other people trained for other microscopy image segmentation problems may not be very useful, unless the model was pre-trained on a very large set, like ImageNet. This is not commonly truely for microscopy image segmentation problems. 

However, our segmenter employs the "**iterative deep learning**" concept. People can start their training from as few as 5 images, and then iteratively improve the model specific for your problem. You can see more about iterative deep learning in our paper and use the aforementioned sample data to test it out.

Thanks!
